base_model: rtzr/ko-gemma-2-9b-it
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer
token: # 허깅페이스 토큰

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: nebchi/ai-malpyung-maerak
    type: alpaca
output_dir: ./outputs/대화맥락추론
save_safetensors : True

#adapter: qlora
#lora_r: 32
#lora_alpha: 16
#lora_dropout: 0.05
#lora_target_linear: true

sequence_len: 1024
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:


gradient_accumulation_steps: 5
micro_batch_size: 3
num_epochs: 5
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 0.000002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false


gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 20
#warmup_ratio: 0.1
evals_per_epoch: 
eval_table_size:
eval_max_new_tokens: 
saves_per_epoch: 
debug:
deepspeed: /home/ubuntu/moon/axolotl/deepspeed_configs/zero2.json
weight_decay: 0.05
sample_packing: false
fsdp:
fsdp_config:
special_tokens: